''' 
CREDITS TO HACKERRANK FOR THIS CHALLENGE
TASK
You are given a space separated list of integers. If all the integers are positive, then you need to check if any integer is a palindromic integer.

Input Format

The first line contains an integer .  is the total number of integers in the list. 
The second line contains the space separated list of  integers.

Constraints
0 < N < 100

Output Format
Print True if all the conditions of the problem statement are satisfied. Otherwise, print False.

Sample Input
5
12 9 61 5 14 

Sample Output
True

Explanation
Condition 1: All the integers in the list are positive. 
Condition 2: 5 is a palindromic integer.

Hence, the output is True.

SOLVE THIS CHALLENGE IN 3 LINES

'''

s = [int(input())] + [int(i) for i in(input().split())]
if (all(i >= 0 for i in s) and any(str(i) == str(i)[::-1] for i in s[2:])): print(True)
else: print(False)

'''
FIRST LINE: creates a joined list by making a list of the first integer in the input and the string generated by the split function over the input(), then the list comprehension transform into int each element of the string and transform it into a list

SECOND LINE: checks if every element of the ints list is positive
checks if any element of the ints list transformed to strings is the same as                  reversed (palindromic integer), transformed to string to reverse it easier
if these conditions are met, prints True

'''
